#!/bin/bash

# **inc/clearlinux** - Support functions only needed on clearlinux

_XTRACE_INC_CLEARLINUX=$(set +o | grep xtrace)
set -o xtrace

# lsb_release only needs -i, -r, -c, -s
# we're assuming the usage in functions-common GetOSVersion() where
# we only care about $1, the -s is assumed here

# Sample os-release file
# NAME="Clear Linux OS"
# VERSION=1
# ID=clear-linux-os
# ID_LIKE=clear-linux-os
# VERSION_ID=25700
# PRETTY_NAME="Clear Linux OS"
# ANSI_COLOR="1;35"
# HOME_URL="https://clearlinux.org"
# SUPPORT_URL="https://clearlinux.org"
# BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
# PRIVACY_POLICY_URL="http://www.intel.com/privacy"

function lsb_release {
    local vendor

    if [[ -f /lib/os-release ]]; then
        os_RELEASE_FILE="/lib/os-release"
    elif [[ -f /etc/os-release ]]; then
        os_RELEASE_FILE="/etc/os-release"
    elif [[ -f /usr/lib/os-release ]]; then
        os_RELEASE_FILE="/usr/lib/os-release"
    else
        # Give up because it doesn't look like this is ClearLinux after all
        return
    fi

    case $1 in
        -c)
            echo "clearlinux"
            ;;
        -i)
            echo $(source $os_RELEASE_FILE; echo $NAME | tr ' ' '_')
            ;;
        -r)
            echo $(source $os_RELEASE_FILE; echo $VERSION_ID)
            ;;
    esac
}


$_XTRACE_INC_CLEARLINUX
